version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    depends_on: 
      - homeassistant
      - zigbee2mqtt
      - adguard
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/nginx/ssl/cyber0s8.net:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - priv-nginx-net
    restart: unless-stopped

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./data/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - priv-adguard-net
      - priv-mosquitto-net
      - priv-nginx-net
    restart: unless-stopped
    privileged: true
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    volumes:
      - ./data/mosquitto/config:/mosquitto/config:rw
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/log:/mosquitto/log
    networks:
      - priv-mosquitto-net
    restart: unless-stopped
  zigbee2mqtt:
    container_name: zigbee2mqtt
    depends_on: 
      - homeassistant
      - mosquitto
    image: koenkk/zigbee2mqtt
    volumes:
      - ./data/zigbee2mqtt:/app/data
      - /run/udev:/run/udv:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
    networks:
      - priv-mosquitto-net
      - priv-nginx-net
    restart: unless-stopped
    privileged: true

  adguard:
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped
    volumes:
      - ./data/adguard/work:/opt/adguardhome/work
      - ./data/adguard/conf:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 68:68/udp
      - 3000:3000
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
    networks:
      - priv-nginx-net
      - priv-adguard-net

networks:
  priv-adguard-net:
  priv-mosquitto-net:
  priv-nginx-net:
