version: '3'
services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest' 
    container_name: nginxproxymanager
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt 
    networks:
      - priv-nginx-net
    restart: unless-stopped 

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - priv-adguard-net
      - priv-mosquitto-net
      - priv-nginx-net
    restart: unless-stopped
    privileged: true

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - priv-mosquitto-net
    restart: unless-stopped

  zigbee2mqtt:
    container_name: zigbee2mqtt
    depends_on: 
      - homeassistant
      - mosquitto
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udv:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
    networks:
      - priv-mosquitto-net
      - priv-nginx-net
    restart: unless-stopped
    privileged: true

  adguard:
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 68:68/udp
      - 3000:3000
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
    networks:
      - priv-nginx-net
      - priv-adguard-net

networks:
  priv-adguard-net:
  priv-mosquitto-net:
  priv-nginx-net:
