ptz_location:
  name: PTZ Location
  description: If your device supports PTZ, you will be able to move it to a specified location
  target:
    entity:
      integration: imou_life
      domain: camera
  fields:
    horizontal:
      name: Horizontal
      description: "Horizontal position."
      default: 0
      selector:
        number:
          min: -1
          max: 1
          step: 0.1
    vertical:
      name: Vertical
      description: "Vertical position."
      default: 0
      selector:
        number:
          min: -1
          max: 1
          step: 0.1
    zoom:
      name: Zoom
      description: "Zoom."
      default: 0
      selector:
        number:
          min: 0
          max: 1
          step: 0.1
ptz_move:
  name: PTZ Move
  description: If your device supports PTZ, you will be able to move it around
  target:
    entity:
      integration: imou_life
      domain: camera
  fields:
    operation:
      name: Operation
      description: "Operation to execute."
      selector:
        select:
          options:
            - "UP"
            - "DOWN"
            - "LEFT"
            - "RIGHT"
            - "UPPER_LEFT"
            - "BOTTOM_LEFT"
            - "UPPER_RIGHT"
            - "BOTTOM_RIGHT"
            - "ZOOM_IN"
            - "ZOOM_OUT"
            - "STOP"
    duration:
      name: Duration
      description: "Duration in milliseconds."
      default: 1000
      selector:
        number:
          min: 100
          max: 10000
          step: 100
