- id: '1645532422727'
  alias: Toggle Living Room lights
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: fdc47dcbe87bf0a577ba84041d1dea4a
    type: action
    subtype: 2_single
    discovery_id: 0x385cfbfffe7447f3 action_2_single
  condition: []
  action:
  - type: toggle
    device_id: 2384002d6407d4d3e98e76571c3691ce
    entity_id: 13c66e16dcc9bdcf835edc31cd0e9681
    domain: light
  mode: single
- id: '1662411324262'
  alias: Turn on Counter lights when movement is detected
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: b5b82ec695758901879fc898e0c05502
    entity_id: 2913f47a72dbf0bdcd37c960b544b8c6
    domain: binary_sensor
  condition:
  - condition: device
    type: is_off
    device_id: f42749587d13d491e0c31f2d91abdf6f
    entity_id: 5662e243cd72c1e3a1f58a2feedc3b0f
    domain: switch
  action:
  - type: turn_on
    device_id: f42749587d13d491e0c31f2d91abdf6f
    entity_id: 5662e243cd72c1e3a1f58a2feedc3b0f
    domain: switch
  mode: single
- id: '1662667912082'
  alias: Turn off Counter lights when movement is not detected for a while
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: b5b82ec695758901879fc898e0c05502
    entity_id: 2913f47a72dbf0bdcd37c960b544b8c6
    domain: binary_sensor
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: device
    type: is_on
    device_id: f42749587d13d491e0c31f2d91abdf6f
    entity_id: 5662e243cd72c1e3a1f58a2feedc3b0f
    domain: switch
  action:
  - type: turn_off
    device_id: f42749587d13d491e0c31f2d91abdf6f
    entity_id: 5662e243cd72c1e3a1f58a2feedc3b0f
    domain: switch
  mode: single
- id: '1662669567182'
  alias: Notify when Fridge door is open for too long
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: f6faae63a3872a8b11ab2f01c09148ee
    entity_id: binary_sensor.fridge_door_sensor_contact
    domain: binary_sensor
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    data:
      title: Fridge Door
      message: Fridge door is open for too long
  mode: single
- id: '1699389447973'
  alias: Jaime leaves Home notification
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.flejz
      zone_entity: zone.home
      notify_device: 5845a97549e1c4e14d675247ebe249fa
- id: '1699389807717'
  alias: Turn off all the lights when saying good night
  description: ''
  trigger:
  - platform: conversation
    command: Good night
  - platform: conversation
    command: Turn off all the lights
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.good_night
    metadata: {}
  mode: single
- id: '1699390952848'
  alias: Turn off all lights when all people leave
  description: ''
  trigger:
  - platform: state
    entity_id:
    - zone.home
    attribute: persons
    to: '0'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.good_night
    metadata: {}
  mode: single
- id: '1699429478602'
  alias: Turn off Counter lights when off switch
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 6826cdcc8a185f06459efe0d584a5f30
    type: click
    subtype: 'off'
    discovery_id: 0x04cd15fffe319b86 click_off
  condition: []
  action:
  - type: turn_off
    device_id: f42749587d13d491e0c31f2d91abdf6f
    entity_id: 5662e243cd72c1e3a1f58a2feedc3b0f
    domain: switch
  mode: single
- id: '1699429543644'
  alias: Turn on Counter lights when on switch
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 6826cdcc8a185f06459efe0d584a5f30
    type: click
    subtype: 'on'
    discovery_id: 0x04cd15fffe319b86 click_on
  condition: []
  action:
  - type: turn_on
    device_id: f42749587d13d491e0c31f2d91abdf6f
    entity_id: 5662e243cd72c1e3a1f58a2feedc3b0f
    domain: switch
  mode: single
- id: '1702158781903'
  alias: Toggle Dining Table Light
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: fdc47dcbe87bf0a577ba84041d1dea4a
    type: action
    subtype: 1_single
    discovery_id: 0x385cfbfffe7447f3 action_1_single
  condition: []
  action:
  - type: toggle
    device_id: 40ec9f1e1757ba6d8262d28c082518c6
    entity_id: 3506b0165e403f62362a4f0d6e182fc0
    domain: light
  mode: single
- id: '1732362111735'
  alias: Outdor Christmas Lights toggle
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: 0
  - trigger: sun
    event: sunrise
    offset: 0
  conditions: []
  actions:
  - type: toggle
    device_id: 66a40cdd84c2e5a8b7cb96dd9e19f08b
    entity_id: 565dc2709c5ff204ac2c0869b4ae420a
    domain: switch
  mode: single
