# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

browser_mod:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

wake_on_lan:
  mac: 60:AB:14:7A:EB:02

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.25.0.5
