# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

browser_mod:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml

wake_on_lan:
  mac: 60:AB:14:7A:EB:02

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.0.0.0/8

emulated_hue:
  type: alexa
  host_ip: 192.168.178.203
  listen_port: 80
  expose_by_default: false
  exposed_domains:
    - light
    - media_player
  entities:
    light.broom_lights:
      hidden: false
    light.office_lights:
      hidden: false
    light.corner_light:
      hidden: false
    light.living_room_light:
      hidden: false
    light.bar_light:
      hidden: false
    light.kitchen_light:
      hidden: false
    switch.kitchen_counter_light:
      hidden: false
    media_player.tv:
      hidden: false
