# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

browser_mod:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

wake_on_lan:
  mac: 60:AB:14:7A:EB:02

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.0.0.0/24
    - 172.19.0.0/16
    - 172.22.0.0/16
    - 172.23.0.0/16
    - 172.31.0.0/16
    - 192.0.0.0/24
    - 192.168.0.0/16
    - 172.19.0.5
    - 172.22.0.5
    - 172.23.0.2
    - 172.31.0.5
    - 192.168.48.5
    - 172.20.0.5
    - 172.26.0.5
    - 172.26.0.2
